### ISSUE TITLE
Auto generate schemas for custom objects

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/stix4doge#2]
We currently generate a lot of custom STIX objects in this repo

https://github.com/muchdogesec/stix4doge/tree/main/generators/custom-objects

These should have proper JSON schemas defined

We currently add placeholders for these in the code

https://github.com/muchdogesec/stix4doge/blob/main/generators/extension-definition.py#L40

We now need to create them automatically using the definition inside each object in this repo

e.g. https://github.com/muchdogesec/stix4doge/blob/main/generators/custom-objects/weakness.py#L20

This includes:

* bank-account
* bank-card
* cryptocurrency-transaction
* crytocurrency-wallet
* phone-number
* user-agent
* weakness

You can see an example of the schemas needed by looking at the core STIX object schemas;

https://github.com/oasis-open/cti-stix2-json-schemas/tree/master/schemas

We should save all JSON schemas as defined for each object (https://github.com/muchdogesec/stix4doge/commit/eb46745edbdd8fb58d9f3ed9bf04884cdc8cf049)

**Comment by fqrious** [comment]
Alright, a lot of refactoring need to be done so another python program can simply import with `from module import Weakness, Phonenumber`

**Comment by himynamesdave** [comment]
Yes, sure. Go for it. I think it will help us going forward to get this repo in order.

**Comment by himynamesdave** [comment]
@fqrious just one thing to note, if we change the URLs of the object in this repo, it will cause breaking changes to other tools.

Ideally try and keep the same paths.

If not, just let me know the changes and I'll update downstream tools

**Comment by fqrious** [comment]
Automatically generating schema is not possible, it'll have to be handwritten...  All the object schemas in [cti-stix2-json-schemas](https://github.com/oasis-open/cti-stix2-json-schemas/tree/master/schemas) were written by hand

**Comment by himynamesdave** [comment]
In that case, I can work on generating the schemas @fqrious
